#pragma once

#define APP_NAME "SCM - by LUNOVU"
#define APP_VERSION_MAJOR 0
#define APP_VERSION_MINOR 1

#define APP_ORG_DOMAIN "www.lunovu.com"
#define APP_ORG_NAME "LUNOVU GmbH"

#define LUNO_LOG_TYPE_MESSAGE 0
#define LUNO_LOG_TYPE_ERROR 1
#define LUNO_LOG_TYPE_WARNING 2
#define LUNO_LOG_TYPE_ACS_MESSAGE 3
#define LUNO_LOG_TYPE_ACS_ERROR 4
#define LUNO_LOG_TYPE_ACS_WARNING 5
#define LUNO_LOG_TYPE_ACS_ERROR_GONE 6
#define LUNO_LOG_TYPE_INTERNAL_MESSAGE 10
#define LUNO_LOG_TYPE_INTERNAL_WARNING 11
#define LUNO_LOG_TYPE_INTERNAL_ERROR 12
#define LUNO_LOG_TYPE_FATAL_ERROR 13

//General flow steps
#define GF_ERROR -1
#define GF_IDLE 0
#define GF_WIP_SEND_REQ 10
#define GF_WIP_SEND 20
#define GF_WIP_SEND_ACK 30
#define GF_BATCH0_EXE 40
#define GF_BATCH_FAIL 50
#define GF_MEAS_ACK 60
#define GF_WAIT_START_MEAS 70
#define GF_START_MEAS 80
#define GF_MEASUREMENT_FINISHED 90
#define GF_BATCH1_EXE 100
#define GF_MEASUREMENT_IO 110
#define GF_MEASUREMENT_NIO 120
#define GF_Process_FINISHED 130
#define GF_PROCESS_WAIT_FOR_DATA 140
#define GF_Process 150
#define GF_MEASURE_WAIT_FOR_DATA 160
#define GF_CHECK_REPLY 170
#define GF_PROG_ACK 180

#define THREAD_HP 1000
#define THREAD_NP 50
